# Generated by Django 5.0.6 on 2024-06-20 14:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(default=None, max_length=100)),
                ('pieces', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donnée',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('temperature', models.CharField(max_length=100)),
                ('id_capteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_capteur.capteur')),
            ],
        ),
    ]
