# Generated by Django 5.0.6 on 2024-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_capteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='maison',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
